# Generated by Django 4.2.7 on 2025-10-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for video (YouTube, Vimeo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Activities', 'Activities'), ('Playground', 'Playground'), ('Music', 'Music'), ('Reading', 'Reading'), ('Science', 'Science'), ('Cooking', 'Cooking')], default='Activities', max_length=100),
        ),
    ]
