# Generated by Django 4.2 on 2025-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_gallery_url_gallery_image_gallery_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure & Environment'), ('curriculum', 'Curriculum & Learning'), ('teachers', 'Teachers & Staff'), ('wellbeing', 'Child Development & Well-Being'), ('enrichment', 'Exposure & Enrichment'), ('innovative', 'Innovative Add-Ons')], max_length=20)),
                ('icon', models.CharField(help_text='Emoji or icon character', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order within category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': 'About Features',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Kiddoo Preschool', max_length=200)),
                ('subtitle', models.TextField(default='By Aarya International School - Nurturing young minds with world-class facilities, innovative curriculum, and experienced educators')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_content', models.TextField()),
                ('cta_title', models.CharField(default='Join the Kiddoo Family Today!', max_length=200)),
                ('cta_content', models.TextField()),
                ('cta_button_text', models.CharField(default='Enroll Your Child Now', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
