# Generated by Django 4.2 on 2025-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutfeature_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the slide', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle or description text')),
                ('image', models.ImageField(help_text='Background image for the slide', upload_to='home_slider/')),
                ('button_text', models.CharField(default='Learn More', help_text='Text for the call-to-action button', max_length=100)),
                ('button_url', models.CharField(default='/programs', help_text='URL to redirect when button is clicked', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
                'ordering': ['order', 'title'],
            },
        ),
    ]
