# Generated by Django 4.2 on 2025-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('students', 'Happy Students'), ('branches', 'Branches'), ('awards', 'Awards Won'), ('teachers', 'Expert Teachers'), ('years', 'Years Experience'), ('satisfaction', 'Parent Satisfaction')], max_length=20, unique=True)),
                ('value', models.IntegerField(help_text='The numeric value to display')),
                ('label', models.CharField(help_text='Display label for the stat', max_length=100)),
                ('suffix', models.CharField(default='', help_text="Suffix to add (e.g., '+', '%', '')", max_length=10)),
                ('icon', models.CharField(default='FaUsers', help_text='Icon name from react-icons/fa', max_length=50)),
                ('color', models.CharField(default='var(--primary-blue)', help_text='CSS color variable or hex code', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this stat is active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Stat',
                'verbose_name_plural': 'Home Stats',
                'ordering': ['order', 'stat_type'],
            },
        ),
    ]
