# Generated by Django 4.2 on 2025-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_homestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_date_of_birth', models.DateField()),
                ('student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_relationship', models.CharField(default='Parent', max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('preferred_program', models.CharField(choices=[('toddler', 'Toddler Program (2-3 years)'), ('preschool', 'Preschool Program (3-4 years)'), ('pre_k', 'Pre-K Program (4-5 years)')], max_length=20)),
                ('preferred_start_date', models.DateField()),
                ('current_school', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or allergies', null=True)),
                ('medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('emergency_medical_consent', models.BooleanField(default=True)),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or accommodations required', null=True)),
                ('previous_preschool_experience', models.TextField(blank=True, null=True)),
                ('why_choose_us', models.TextField(blank=True, help_text='Why do you want to enroll your child at Kiddoo Preschool?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
