# Generated by Django 4.2.7 on 2025-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Type of media for the slide', max_length=10),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='video',
            field=models.FileField(blank=True, help_text='Background video for the slide', null=True, upload_to='home_slider/videos/'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Poster image for video (shown before video loads)', null=True, upload_to='home_slider/posters/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, help_text='Background image for the slide', null=True, upload_to='home_slider/'),
        ),
    ]
