# Generated by Django 4.2.7 on 2025-10-06 10:40

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_video_support_to_home_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='video',
            field=models.FileField(blank=True, help_text='Background video for the slide (max 15 seconds, MP4 format, max 50MB)', null=True, upload_to='home_slider/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), api.models.validate_video_file_size, api.models.validate_video_duration]),
        ),
    ]
