# Generated by Django 4.2.7 on 2025-10-16 18:23

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_video_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='video',
            field=models.FileField(blank=True, help_text='Background video for the slide (max 15 seconds, MP4 format, max 50MB)', null=True, upload_to='home_slider/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), api.models.validate_video_file_size]),
        ),
    ]
