# Generated by Django 4.2.7 on 2025-10-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gallery_video_url_alter_homeslider_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=150),
        ),
    ]
